TRChat/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomePageView

urlpatterns = [url(r'^(?!.)', HomePageView.as_view(), name='home')]

chat_message/urls.py
from django.conf.urls import url

from chat_message.views import CreateMessageView

urlpatterns = [
    url(r'^(?P<room>\d)', CreateMessageView.as_view(), name='create_message')
]

chat_room/urls.py
from django.conf.urls import url

from chat_room.views import CreateRoomView

urlpatterns = [url(r'^(?!.)', CreateRoomView.as_view(), name='rooms_list')]

untitled1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^(?!.)', include('TRChat.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^room/', include('chat_message.urls')),
    url(r'^roms/', include('chat_room.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

TRChat/models.py
# Create your models here.

chat_message/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from chat_room.models import Room


# Create your models here.

class Message(models.Model):
    author = models.ForeignKey(User)
    text = models.CharField(max_length=255)
    timestamp = models.DateTimeField(default=timezone.now)
    room = models.ForeignKey(Room)

    def __str__(self):
        return '{}: {}'.format(self.author, self.text)

chat_room/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    creator = models.ForeignKey(User)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

chatMessages/forms.py
from django import forms

from chatMessages.models import ChatMessage


class MessageForm(forms.ModelForm):
    class Meta:
        fields = ['text']
        model = ChatMessage

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.chat = kwargs.pop('chat', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        message = super().save(commit=False)
        message.author = self.user
        message.chat = self.chat
        message.save()
        return message

chat_message/forms.py
from django import forms

from chat_message.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        fields = ['text']
        model = Message

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.room = kwargs.pop('room', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        message = super().save(commit=False)
        message.author = self.user
        message.room = self.room
        message.save()
        return message

TRChat/views.py
from __future__ import unicode_literals

from django.views.generic.base import TemplateView


# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        return context

chat_message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView

from chat_message.forms import MessageForm
from chat_room.models import Room


# Create your views here.

class CreateMessageView(LoginRequiredMixin, CreateView):
    form_class = MessageForm
    template_name = 'chat_message/message_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['room'] = get_object_or_404(Room, id=self.kwargs['room'])
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['room'] = get_object_or_404(Room, id=self.kwargs['room'])
        return kwargs

    def get_success_url(self):
        return reverse('create_message', kwargs=dict(room=self.kwargs['room']))

chat_room/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

from chat_room.models import Room


# Create your views here.

class CreateRoomView(LoginRequiredMixin, CreateView):
    model = Room
    template_name = "chat_room/room_create_bootsrtap.html"
    fields = ['name']
    success_url = '/roms'

    def get_context_data(self, **kwargs):
        context = super(CreateRoomView, self).get_context_data(**kwargs)
        context['objects'] = self.model.objects.all()
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(CreateRoomView, self).form_valid(form)

templates/base.html
{% extends 'bootstrap.html' %}
{% load bootstrap3 %}

{% block bootstrap3_content %}


    {% block header %}
        <nav class="navbar navbar-inverse navbar-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">

                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">TRPO - CHAT</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                        {% if request.user.is_authenticated %}
                            <li><a>Wellcome - {{ request.user.username }}</a></li>
                            <li><a href="{% url 'rooms_list' %}">Rooms</a></li>
                            <li><a href="/accounts/logout">Logout</a></li>
                        {% else %}
                            <li><a href="/accounts/login">Login</a></li>{% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    {% endblock %}

    {% block content %}
        (no content)
    {% endblock %}
    {% block footer %}
        <footer style="position: absolute;bottom: 0;width: 100%;height: 60px;background-color: #f5f5f5;">
            <div class="container"><p style="margin: 20px 0">Сборная ТРПО по чатам!</p></div>
        </footer>
    {% endblock %}


{% endblock %}

templates/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

templates/chat_message/message_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    TRPO - Chat in {{ room.name }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-default" style="">
                    <div class="panel-heading" id="accordion">
                        <span class="glyphicon glyphicon-comment"></span> {{ room.name }}
                        <div class="btn-group pull-right">
                            <a type="button" class="btn btn-default btn-xs" data-toggle="collapse"
                               data-parent="#accordion" href="#collapseOne">
                                <span class="glyphicon glyphicon-chevron-down"></span>
                            </a>
                        </div>
                    </div>
                    <div class="panel-collapse body" id="collapseOne">
                        <div class="panel-body" style="height: 30em;overflow: scroll">
                            <ul class="chat">
                                {% for message in room.message_set.all %}
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">{{ message.author }}</strong>
                                            <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>{{ message.timestamp.now }}
                                            </small>
                                        </div>

                                        <p>{{ message.text }}</p>
                                    </div>
                                {% endfor %}
                                </span>
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <div class="input-group">
                                <form class="form-inline" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_form form %}
                                    {% buttons %}
                                        <button class="btn btn-warning btn-sm">Send</button>
                                    {% endbuttons %}
                                </form>

                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/chat_room/room_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Rooms</h2>
<ul>
    {% for room in objects %}
        <li><a href="/room/{{ room.id }}">{{ room.name }}</a></li>
    {% endfor %}
</ul>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
<a href="/accounts/logout">Logout</a>
</body>
</html>

templates/chat_room/room_create_bootsrtap.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Rooms{% endblock %}
{% block content %}
    <div class="container">

        <ul class="list-group">
            {% for room in objects %}
                <li class="list-group-item"><a href="/room/{{ room.id }}">{{ room.name }}</a></li>
            {% endfor %}
        </ul>
        <form action="" method="post" class="form-inline">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create">
        </form>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
    TRPO - Chat
{% endblock %}



{% block content %}
    <div class="container">
        <div class="starter-template">
            <h1><abbr title="Технология разработки программного обеспечения">TRPO</abbr>-Chat Wellcome!</h1>
            <p class="lead">Glad to see you here! Please <a href="/accounts/login">Login</a> or <a
                    href="/accounts/register">Register</a> to start use this app</p>
        </div>
    </div><!-- /.container -->
{% endblock %}